use database customer_shopping_behavior

# What is the total revenue generated by male vs. female customers?
select Gender, sum(`Purchase Amount (USD)`) from customer_shopping_behavior
group by Gender;

# Which customers used a discount but still spent more than the average purchase amount?
select `ï»¿Customer ID`,`Purchase Amount (USD)`  from customer_shopping_behavior
where `Discount Applied`='Yes' and `Purchase Amount (USD)`>= (select avg(`Purchase Amount (USD)`) from customer_shopping_behavior);

# Which are the top 5 products with the highest average review rating?
select `Item Purchased`, avg(`Review Rating`) from customer_shopping_behavior
group by `Item Purchased`
order by avg(`Review Rating`) desc 
limit 5;

#Compare the average Purchase Amount between standard and express shipping?
select `Shipping Type`, avg(`Purchase Amount (USD)`)
from customer_shopping_behavior
where `Shipping Type` in ('Standard', 'Express')
group by `Shipping Type`;


# Do Subscribed customer spend more? Compare average spend and total revenue between subscribers and non-subscribers?
select `Subscription Status`, count(`ï»¿Customer ID`),avg(`Purchase Amount (USD)`), sum(`Purchase Amount (USD)`)
from customer_shopping_behavior
group by `Subscription Status`;


# Which 5 products have the highest percentage of purchases with discount applied?
 select `Item Purchased`, sum(case when `Discount Applied` = 'Yes' then 1 else 0 end)/count(*) * 100 as discount_rate
 from customer_shopping_behavior
 group by `Item Purchased`
 order by discount_rate desc
 limit 5;


# Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment. 
with customer_type as
(select `ï»¿Customer ID`, `Previous Purchases`, 
case 
when `Previous Purchases` = 1 then 'New'
when `Previous Purchases` between 2 and 10 then 'Returning'
else 'Loyal'
end as customer_segment
from customer_shopping_behavior 
)

select customer_segment, count(*) as "Number of Customers"
from customer_type
group by customer_segment;


# What are the top 3 most purchased products within each category?
with item_counts as 
(
select `Category`, `Item Purchased`, count(`ï»¿Customer ID`) as total_orders,
row_number() over(partition by `Category` order by count(`ï»¿Customer ID`) desc) as item_rank
from customer_shopping_behavior
group by `Category`, `Item Purchased`
)

select item_rank, `Category`, `Item Purchased`, total_orders
from item_counts
where item_rank <= 3; 


# Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select `Subscription Status`, count(`ï»¿Customer ID`) as repeat_buyers
from customer_shopping_behavior
where `Previous Purchases` >5
group by `Subscription Status`;


#What is the revenue contribution of each age group?
select age_group,
sum(`Purchase Amount (USD)`) as total_revenue
from customer_shopping_behavior
group by age_group
order by total_revenue desc;

